### ISSUE TITLE
less compatibility issues

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/vscode-samples#2]
I was just attempting to get my feet wet with the typescript node debugging support when I tumbled upon the following issue running the `watch` task:

```
c:\source\node-express-typescript\node_modules\accord\lib\index.js:31
      throw new Error(name + " version " + version + " is not currently supported");
      ^
Error: less version 1.7.5 is not currently supported
    at Object.exports.load (c:\source\node-express-typescript\node_modules\accord\lib\index.js:31:13)
    at Object.<anonymous> (c:\source\node-express-typescript\node_modules\gulp-less\index.js:9:29)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\source\node-express-typescript\gulpfile.js:2:12)
    at Module._compile (module.js:435:26)
```

I haven't checked the javascript example but I presume both suffer the same problem.

**Comment by bowdenk7** [comment]
How did you end up with `accord`?

Error is coming from `node_modules\accord\lib\index.js:31` but accord isn't listed in `package.json`?

I was able to run watch just fine (after global installing gulp as you noted in your PR https://github.com/Microsoft/vscode-samples/pull/1).

**Comment by johnnyreilly** [comment]
Hmmm. Will reattempt and see. Trying to remember if I'd upgraded to npm 3 at that point and wondering if it had any bearing...

**Comment by chrisdias** [comment]
hi - i am seeing this error too, sorry about it.  i'm swamped after the thanksgiving break and will get to this asap.  pull requests are welcome :)

**Comment by djabraham** [comment]
I made the following change to package.json and got it building again, but I did not do any extensive testing..

```
"less-middleware": "1.0.x",

"less-middleware": "^2.0.0",
```

After changing that, I cleaned the less and less-middleware folders from npm_modules and ran npm install again. It seems the hard version reference was causing an older version of Less to be pulled.

**Comment by johnnyreilly** [comment]
Yup that seems to fix it - do you want to issue a PR @djabraham ?

**Comment by chrisdias** [comment]
I’ll fix it, no need for a PR.

Thanks for doing this!

**Comment by chrisdias** [comment]
fixed with https://github.com/Microsoft/vscode-samples/commit/9cc7b89cabb42b419db6d4649a43011fe7abc20b

**Comment by johnnyreilly** [comment]
Sweet.
