### ISSUE TITLE
Accessing the Clipboard

### ISSUE THREAD

**Issue by MisterJames** [Microsoft/vscode-samples#4]
I'd like to access image data that is on the clipboard, with the intent of supporting "pasting" an image into a markdown file. I don't want to paste, per se, I just want a command to "insert image from clipboard via blob upload".

Rather than actually putting the image in, I'd like the image markdown inserted. In the background, I'd like to upload the image to Azure blob storage via the Azure API, then get the path for the blob and use that in the markdown.

I have a handle (via other samples) on how to contribute commands and keybinding, how to get configuration, and how to execute code, but I'm not seeing any samples that interact with the clipboard. I also can't see any API docs that would suggest this is available. Is there another approach one could take to implement this? Is there a way one could go about accessing the data on the clipboard from a VS Code extension?

**Comment by egamma** [comment]
Currently we do not expose API for accessing the clipboard.
See the discussion in this issue microsoft/vscode#217. In particular this [comment](https://github.com/Microsoft/vscode/issues/217#issuecomment-171348862).

 Feel free to comment and reopen.

**Comment by chrisdias** [comment]
closing.
